### ISSUE TITLE
Use cURL instead of file_get_contents

### ISSUE THREAD

**Issue by HetIsNiels** [HetIsNiels/NielsBot#3]
See https://github.com/HetIsNiels/NielsBot/blob/master/NielsBot/Telegram/Telegram.php#L29

**Comment by matthijs186** [comment]
Reproducable.
![reproduction image](http://i.imgur.com/hAeWvbw.png)

**Comment by HetIsNiels** [comment]
Now using cURL but the bug is caused by Telegram parsing it as markdown.
